<?php

require "includes/header.php";

?>

<div class="reference-home">
    <section class="reference-hero">
        <div class="hero-copy"><span class="reference-kicker">CENTRAL DE INVESTIGAÇÕES</span><h1>RESOLVA MISTÉRIOS.<br><em>DOMINE A MATEMÁTICA.</em></h1><p>Entre no mundo do Detetive dos Dados e use sua mente para analisar pistas, interpretar gráficos e desvendar casos incríveis!</p><div class="reference-actions"><a class="reference-primary" href="jogos/index.php">⌕ &nbsp; COMEÇAR AGORA</a><a class="reference-secondary" href="conteudos.php#matematica">▶ &nbsp; ASSISTIR VÍDEO</a></div></div>
        <div class="reference-art" aria-label="Detetive e robô analisando dados"><div class="art-lamp">◒</div><div class="art-chart">x̄ = 1/n ∑ xᵢ<br><span>▥ ▥ ▥ ▥</span></div><div class="art-detective"><span class="detective-hat"></span><span class="detective-face">◉</span><span class="detective-coat"></span><span class="magnifier">◯</span></div><div class="art-robot"><span class="robot-glow"></span><span class="ai-head">⌣⌣</span><span class="ai-body">▥</span><span class="ai-arm left"></span><span class="ai-arm right"></span></div><div class="art-note">QUEM É O<br>CULPADO?<b>?</b></div></div>
    </section>
    <section class="reference-benefits" id="sobre"><div class="reference-benefits-track"><div class="reference-benefits-group"><a class="benefit-card" href="jogos/media.php"><span class="benefit-icon">⌕</span><b>RESOLVA<br>CASOS</b><small>Analise dados, gráficos<br>e encontre a verdade<br>por trás dos mistérios.</small></a><a class="benefit-card" href="jogos/palavras.php"><span class="benefit-icon">▣</span><b>PALAVRAS<br>INTELIGENTES</b><small>Misture prefixos e sufixos<br>para desbloquear novas<br>palavras.</small></a><a class="benefit-card" href="conteudos.php#matematica"><span class="benefit-icon">◉</span><b>DESAFIOS<br>MATEMÁTICOS</b><small>Exercite sua mente com<br>desafios de média, moda,<br>mediana e muito mais.</small></a><a class="benefit-card" href="ranking.php"><span class="benefit-icon">♜</span><b>RANKING E<br>CONQUISTAS</b><small>Ganhe XP, suba no ranking<br>e conquiste medalhas<br>incríveis!</small></a><a class="benefit-card" href="jogos/index.php"><span class="benefit-icon">♙</span><b>NOVOS CASOS<br>SEMPRE</b><small>Novos mistérios e desafios<br>disponíveis toda semana<br>para você resolver!</small></a></div><div class="reference-benefits-group" aria-hidden="true"><a class="benefit-card" href="jogos/media.php" tabindex="-1"><span class="benefit-icon">⌕</span><b>RESOLVA<br>CASOS</b><small>Analise dados, gráficos<br>e encontre a verdade<br>por trás dos mistérios.</small></a><a class="benefit-card" href="jogos/palavras.php" tabindex="-1"><span class="benefit-icon">▣</span><b>PALAVRAS<br>INTELIGENTES</b><small>Misture prefixos e sufixos<br>para desbloquear novas<br>palavras.</small></a><a class="benefit-card" href="conteudos.php#matematica" tabindex="-1"><span class="benefit-icon">◉</span><b>DESAFIOS<br>MATEMÁTICOS</b><small>Exercite sua mente com<br>desafios de média, moda,<br>mediana e muito mais.</small></a><a class="benefit-card" href="ranking.php" tabindex="-1"><span class="benefit-icon">♜</span><b>RANKING E<br>CONQUISTAS</b><small>Ganhe XP, suba no ranking<br>e conquiste medalhas<br>incríveis!</small></a><a class="benefit-card" href="jogos/index.php" tabindex="-1"><span class="benefit-icon">♙</span><b>NOVOS CASOS<br>SEMPRE</b><small>Novos mistérios e desafios<br>disponíveis toda semana<br>para você resolver!</small></a></div></div></section>
    <section class="reference-stats" id="contato"><div><strong>◉</strong><b>+250</b><small>CASOS RESOLVIDOS</small></div><div><strong>♟</strong><b>+12.000</b><small>DETETIVES ATIVOS</small></div><div><strong>✤</strong><b>+80</b><small>DESAFIOS DISPONÍVEIS</small></div><div><strong>♜</strong><b>+50</b><small>CONQUISTAS PARA GANHAR</small></div></section>
</div>

<?php

require "includes/footer.php";

?>