<?php
require_once "../includes/config.php";
require_once "../includes/auth.php";
require_once "../includes/functions.php";
exigirLogin();
$bancos = [
 [["nome"=>"Prefixo","frase"=>"feliz + in = ?","instrucao"=>"Qual palavra completa a transformação?","opcoes"=>["infeliz","felizmente","infelizmente","felicidade"],"resposta"=>"infeliz"],["nome"=>"Prefixo","frase"=>"possível + im = ?","instrucao"=>"Qual palavra recebe o prefixo negativo?","opcoes"=>["impossível","possibilidade","possivelmente","despossível"],"resposta"=>"impossível"]],
 [["nome"=>"Sufixo","frase"=>"feliz + mente = ?","instrucao"=>"Escolha a palavra formada pelo sufixo.","opcoes"=>["infeliz","felizmente","felicidade","felizão"],"resposta"=>"felizmente"],["nome"=>"Sufixo","frase"=>"rápido + mente = ?","instrucao"=>"Que advérbio é formado pelo sufixo?","opcoes"=>["rapidez","rapidamente","enr rápido","irrapido"],"resposta"=>"rapidamente"]],
 [["nome"=>"Derivação","frase"=>"leal + dade = ?","instrucao"=>"Que substantivo nasce dessa base mais o sufixo?","opcoes"=>["lealdade","desleal","lealmente","leitor"],"resposta"=>"lealdade"],["nome"=>"Derivação","frase"=>"real + idade = ?","instrucao"=>"Qual palavra é formada por derivação sufixal?","opcoes"=>["realidade","irreal","realmente","realeza"],"resposta"=>"realidade"]],
 [["nome"=>"Prefixo negativo","frase"=>"feliz + in = ?","instrucao"=>"Use o prefixo que muda o sentido da palavra.","opcoes"=>["infeliz","felizmente","felicidade","refeliz"],"resposta"=>"infeliz"],["nome"=>"Prefixo negativo","frase"=>"legal + i = ?","instrucao"=>"Qual palavra expressa o sentido contrário?","opcoes"=>["ilegal","legalmente","legalidade","relegal"],"resposta"=>"ilegal"]],
 [["nome"=>"Parassíntese","frase"=>"noite + en + ecer = ?","instrucao"=>"Qual verbo indica tornar-se noite?","opcoes"=>["anoitecer","noiteiro","desnoite","noturno"],"resposta"=>"anoitecer"],["nome"=>"Parassíntese","frase"=>"triste + en + ecer = ?","instrucao"=>"Qual verbo indica tornar-se triste?","opcoes"=>["entristecer","tristeza","tristemente","destriste"],"resposta"=>"entristecer"]],
 [["nome"=>"Desafio final","frase"=>"feliz → infelizmente","instrucao"=>"Identifique a formação usada.","opcoes"=>["derivação prefixal e sufixal","composição por justaposição","abreviação","onomatopeia"],"resposta"=>"derivação prefixal e sufixal"],["nome"=>"Desafio final","frase"=>"des + leal + dade = ?","instrucao"=>"Qual processo combina prefixo e sufixo?","opcoes"=>["derivação prefixal e sufixal","composição por aglutinação","sigla","redução"],"resposta"=>"derivação prefixal e sufixal"]]
];
$usuarioAtual = usuarioId();
$questoesGeradas = $_SESSION["palavras_geradas"] ?? [];
foreach ($questoesGeradas as $nivelGerado => $questaoGerada) { $bancos[$nivelGerado][] = $questaoGerada; }
$selecionadas = $_SESSION["palavras_selecionadas"] ?? null;
if ($selecionadas === null) { $selecionadas = []; foreach ($bancos as $nivel => $banco) { $opcoes = array_keys($banco); shuffle($opcoes); foreach ($opcoes as $opcao) { if (!questaoJaRespondida($conn, $usuarioAtual, "portugues-{$nivel}-{$opcao}")) { $selecionadas[$nivel] = $opcao; break; } } if (!isset($selecionadas[$nivel])) { $variacoes = [["nome"=>"Prefixo","frase"=>"des + fazer = ?","instrucao"=>"Qual palavra é formada pelo prefixo?","opcoes"=>["desfazer","fazermente","refazer","fazedor"],"resposta"=>"desfazer"],["nome"=>"Sufixo","frase"=>"casa + eiro = ?","instrucao"=>"Qual palavra nasce com o sufixo indicado?","opcoes"=>["caseiro","casarão","descasa","casual"],"resposta"=>"caseiro"],["nome"=>"Derivação","frase"=>"pedra + eiro = ?","instrucao"=>"Identifique a palavra derivada.","opcoes"=>["pedreiro","pedregulho","pedraço","pedrinha"],"resposta"=>"pedreiro"],["nome"=>"Prefixo negativo","frase"=>"regular + ir = ?","instrucao"=>"Qual palavra expressa o sentido contrário?","opcoes"=>["irregular","regularidade","regularmente","regulador"],"resposta"=>"irregular"],["nome"=>"Parassíntese","frase"=>"velho + en + ecer = ?","instrucao"=>"Qual verbo indica tornar-se velho?","opcoes"=>["envelhecer","velhice","velhamente","desvelho"],"resposta"=>"envelhecer"],["nome"=>"Desafio final","frase"=>"des + leal + dade = ?","instrucao"=>"Qual processo combina prefixo e sufixo?","opcoes"=>["derivação prefixal e sufixal","composição","sigla","redução"],"resposta"=>"derivação prefixal e sufixal"]]; $questaoGerada = $variacoes[$nivel]; $bancos[$nivel][] = $questaoGerada; $questoesGeradas[$nivel] = $questaoGerada; $_SESSION["palavras_geradas"] = $questoesGeradas; $selecionadas[$nivel] = count($bancos[$nivel]) - 1; } } $_SESSION["palavras_selecionadas"] = $selecionadas; }
$dificuldades = ["Fácil", "Fácil", "Médio", "Médio", "Difícil", "Avançado"];
$fases = []; foreach ($bancos as $nivel => $banco) { $fases[] = array_merge($banco[$selecionadas[$nivel]], ["id" => "portugues-{$nivel}-{$selecionadas[$nivel]}", "xp" => 15 + ($nivel * 6), "dificuldade" => $dificuldades[$nivel]]); }
$fase = (int) ($_SESSION["palavras_fase"] ?? 0); $pontos = (int) ($_SESSION["palavras_pontos"] ?? 0); $mensagem = ""; $classe = ""; $finalizado = false;
$stmtXp = $conn->prepare("SELECT xp FROM usuarios WHERE id = ?");
$stmtXp->bind_param("i", $usuarioAtual);
$stmtXp->execute();
$xpTotal = (int) ($stmtXp->get_result()->fetch_assoc()["xp"] ?? 0);
if (isset($_GET["reiniciar"])) { unset($_SESSION["palavras_fase"], $_SESSION["palavras_pontos"], $_SESSION["palavras_selecionadas"]); header("Location: palavras.php"); exit; }
if ($_SERVER["REQUEST_METHOD"] === "POST" && isset($fases[$fase])) {
    if (($_POST["resposta"] ?? "") === $fases[$fase]["resposta"]) { $xpFase = (int) $fases[$fase]["xp"]; $pontos += $xpFase; adicionarXP($conn, $usuarioAtual, $xpFase); marcarQuestaoRespondida($conn, $usuarioAtual, $fases[$fase]["id"], "Laboratório das Palavras"); $fase++; $_SESSION["palavras_fase"] = $fase; $mensagem = "Mistura correta. Você ganhou {$xpFase} XP."; $classe = "success"; }
    else { $mensagem = "Essa combinação ainda não forma a palavra certa."; $classe = "error"; }
    $_SESSION["palavras_pontos"] = $pontos;
    if ($fase >= count($fases)) { registrarPartida($conn, usuarioId(), "Laboratório das Palavras", "Avançado", $pontos, count($fases), 0, false); $finalizado = true; unset($_SESSION["palavras_fase"], $_SESSION["palavras_pontos"], $_SESSION["palavras_selecionadas"]); }
}
require "../includes/header.php";
$questao = $fases[$fase] ?? null;
echo '<div class="total-score">XP acumulado: ' . $xpTotal . '</div>';
?>
<section class="game-shell words-shell"><aside class="game-sidebar"><a class="side-brand" href="../index.php">DETETIVE<br><b>DOS DADOS</b></a><a class="side-link" href="media.php">Detetive dos Dados</a><a class="side-link active" href="palavras.php">Laboratório</a><a class="side-link" href="../ranking.php">Ranking</a><a class="side-link" href="../perfil.php">Perfil</a></aside><main class="game-main"><div class="game-topline"><span>LABORATÓRIO · NÍVEL <?= min($fase + 1, count($fases)) ?></span><strong><?= $pontos ?> XP</strong></div><div class="game-title"><span class="section-tag">FORMAÇÃO DE PALAVRAS</span><h1>Laboratório das Palavras</h1><p>Leia, misture e descubra o sentido de cada palavra.</p></div><div class="game-progress-label"><span>PROGRESSO DO EXPERIMENTO</span><b><?= min($fase + 1, count($fases)) ?> / <?= count($fases) ?></b></div><div class="case-path"><?php for ($n = 0; $n < count($fases); $n++): ?><span class="path-node <?= $n < $fase ? "done" : ($n === $fase ? "current" : "") ?>"><?= $n + 1 ?></span><?php if ($n < count($fases) - 1): ?><i></i><?php endif; ?><?php endfor; ?></div><?php if ($finalizado): ?><section class="case-board result-panel"><span class="result-mark">OK</span><h2>Laboratório completo</h2><p>Você dominou prefixos, sufixos e derivação.</p><strong class="big-score"><?= $pontos ?> XP</strong><a class="action-button" href="palavras.php?reiniciar=1">Nova experiência</a></section><?php elseif ($questao): ?><section class="case-board words-case-board"><div class="case-note"><span>CASO:</span><strong>O ENIGMA DAS PALAVRAS</strong><p>Experimento <?= $fase + 1 ?> de <?= count($fases) ?><br>Descubra como a palavra foi formada.</p></div><div class="evidence-board"><div class="clue-heading"><span>EXPERIMENTO <?= $fase + 1 ?> / <?= count($fases) ?></span><span class="difficulty-badge difficulty-<?= strtolower($questao["dificuldade"]) ?>"><?= htmlspecialchars($questao["dificuldade"]) ?></span></div><div class="word-equation"><?= htmlspecialchars($questao["frase"]) ?></div><h2><?= htmlspecialchars($questao["instrucao"]) ?></h2><?php if ($mensagem): ?><div class="game-feedback <?= $classe ?>"><?= htmlspecialchars($mensagem) ?></div><?php endif; ?><form method="POST" class="answer-grid"><?php foreach ($questao["opcoes"] as $opcao): ?><label><input type="radio" name="resposta" value="<?= htmlspecialchars($opcao) ?>" required><span><?= htmlspecialchars($opcao) ?></span></label><?php endforeach; ?><button class="action-button" type="submit">Enviar resposta</button></form></div><aside class="case-annotations words-tip"><strong>DICA DE LINGUAGEM</strong><p>Observe a base da palavra.</p><p>Identifique o prefixo.</p><p>Depois procure o sufixo.</p></aside></section><?php endif; ?></main></section>
<?php require "../includes/footer.php"; ?>
